### ISSUE TITLE
Receiving no Data

### ISSUE THREAD

**Issue by BigPun86** [devfd/react-native-geocoder#10]
Hey there! I am trying to use this module in my Android RN15 Project. Unfortunately i don´t receive any data. It doesn´t give me any error too. So i have no clue where to search for the issue. I tried updating the *android/build.gradle* from geocoder to RN 15 which didn´t work...
I hope somebody has an idea or maybe experienced similar issues?

(I call this example in my componentDidMount)

**Comment by devfd** [comment]
Can you tell me on what device / simulator are you running your project ?

**Comment by BigPun86** [comment]
I am using the GenyMotion Emulator

**Comment by devfd** [comment]
ok make sure to install all the google apps. without google play services you cannot access the geocoding service.

I personally use an AVD with an x86 target set to 'Google Api'. it run really smooth when combined with the HAXM accelerator.

**Comment by BigPun86** [comment]
Okay thanks! I used my real device to test it. Works perfectly. But does it make sense (generally) to update react-native in geocoders android/build.gradle?
Thanks again!

**Comment by BigPun86** [comment]
Okay worked with GenyMotion after installing GApps. Thanks @devfd 
If someone has any issues setting up GApps for GenyMotion, this is what helped me: http://stackoverflow.com/questions/17831990/how-do-you-install-google-frameworks-play-accounts-etc-on-a-genymotion-virt
