### ISSUE TITLE
Question: What is the usage limitation?

### ISSUE THREAD

**Issue by bartonhammond** [devfd/react-native-geocoder#11]
Currently I do GeoCoding on my server using MapQuest and I have a limitation.  Should I move the GeoCoding to the device using this package and if so, what limitations would I have?  Do I have to sign up for any service to support this?

Thanks.

**Comment by devfd** [comment]
no sign-up is necessary. this library uses the native capabilities of the device.

the only limitation I see is for non-Google Android devices and old android devices (think Amazon tablets, android 4.1 devices ...). On those devices there is no way to use google geocoding services, so you will have to fall back on an external service (a MapQuest server, or google geocoding api https://developers.google.com/maps/documentation/geocoding/intro)

hope it helps
