### ISSUE TITLE
How to use geocoding?

### ISSUE THREAD

**Issue by sayedatif** [devfd/react-native-geocoder#27]
hey @devfd can you help me how to use it i am bit confused how to integrate it with my current code . I am taking user current location by the following code can you help me how i can integrate geocoeding with it

here is  my current code:

```
navigator.geolocation.getCurrentPosition(
      (position) => {
        this.setState({
          region: {
            latitude: position.coords.latitude,
            longitude: position.coords.longitude, 
            latitudeDelta: LATITUDE_DELTA,
            longitudeDelta: LONGITUDE_DELTA
          }
        });
      },
    );
```

**Comment by devfd** [comment]
@sayedatif this project is from my free time. the least you could do before creating an issue is to read the documentation and have a look at the sample app.

thanks
