### ISSUE TITLE
Nominatim as fallback?

### ISSUE THREAD

**Issue by ramsestom** [devfd/react-native-geocoder#28]
Is there any plan to also support Nominatim (http://wiki.openstreetmap.org/wiki/Nominatim), from openstreetmap, as a fallback geocoding service rather than google maps?
I think it would be more convenient as Nominatim do not limit in the number of daily requests...

EDIT: geocoding service from mapquest used to be free without limit too but I just saw it is no longuer the case :( . But maybe there is some other completely free geocoding service that could be used as fallback... Just found this one: http://services.gisgraphy.com/public/geocoding.html but it requiere you to host your own server to use it for free (else you have to pay if you want to use premium servers)

**Comment by devfd** [comment]
I have yet to find a better geocoding service than google. and anyway it is only used as a fallback so you are very unlikely to hit the quota limit ;)

**Comment by renzified** [comment]
> Is there any plan to also support Nominatim (http://wiki.openstreetmap.org/wiki/Nominatim), from openstreetmap, as a fallback geocoding service rather than google maps?
> I think it would be more convenient as Nominatim do not limit in the number of daily requests...
> 
> EDIT: geocoding service from mapquest used to be free without limit too but I just saw it is no longuer the case :( . But maybe there is some other completely free geocoding service that could be used as fallback... Just found this one: http://services.gisgraphy.com/public/geocoding.html but it requiere you to host your own server to use it for free (else you have to pay if you want to use premium servers)

hello im having a trouble accesing nominatim using fetch api its said i need to have a valid user agent or http referrer
