### ISSUE TITLE
Android: Error: Geocoder not available for this platform

### ISSUE THREAD

**Issue by davidfloegel** [devfd/react-native-geocoder#39]
Hey all,

The plugin works great on ios but on android I'm getting this error? I have followed all steps but not sure what's missing..

Using RN 0.40

Any pointers?

Cheers

**Comment by devfd** [comment]
please see the android documentation about this:

>  The Geocoder class requires a backend service that is not included in the core android framework. The Geocoder query methods will return an empty list if there no backend service in the platform. Use the isPresent() method to determine whether a Geocoder implementation exists.

v0.4.8 addresses this issue by always sending a geocoding request to the web api
