### ISSUE TITLE
Receiving an array with a lot of objects

### ISSUE THREAD

**Issue by desktp** [devfd/react-native-geocoder#44]
Hello,
Reading the README, I was under the impression that the request would return one object with the device's current location. However, when I started testing, I got a huge array with diminishing accuracy. Is that the expected behavior? Is there a pattern to the objects? Is the returned array always the same size?

Also, is it possible to change the locale to get the address in another language?

Code sample:
```
  componentDidMount() {
    navigator.geolocation.getCurrentPosition(
      (position) => {
        const latLng = { 
          lat: position.coords.latitude, 
          lng: position.coords.longitude
        };

        Geocoder.geocodePosition(latLng).then(res => {
          this.props.setLocation(res);
          console.log(res);
        })
        .catch(err => console.log(err)); 
      },
      (error) => console.log(JSON.stringify(error)),
      { enableHighAccuracy: true, timeout: 20000, maximumAge: 1000 }
    );
  }
```

`latLng`: 
`{ lat: -6.228769999999999, lng: -35.060759999999995 }`

`res`:
`[ { streetName: null,
    feature: null,
    locale: 'en_US',
    locality: 'Pipa Beach',
    position: { lng: -35.0487735, lat: -6.2289986 },
    adminArea: 'State of Rio Grande do Norte',
    streetNumber: null,
    country: 'Brazil',
    countryCode: 'BR',
    postalCode: null,
    subAdminArea: null,
    formattedAddress: 'Pipa Beach, Tibau do Sul - State of Rio Grande do Norte, Brazil',
    subLocality: null },
  { streetName: null,
    feature: null,
    locale: 'en_US',
    locality: 'Tibau do Sul',
    position: { lng: -35.1048713, lat: -6.2211806 },
    adminArea: 'State of Rio Grande do Norte',
    streetNumber: null,
    country: 'Brazil',
    countryCode: 'BR',
    postalCode: null,
    subAdminArea: null,
    formattedAddress: 'Tibau do Sul - State of Rio Grande do Norte, Brazil',
    subLocality: null },
  { streetName: null,
    feature: '59178-000',
    locale: 'en_US',
    locality: 'Tibau do Sul',
    position: { lng: -35.1048713, lat: -6.2211806 },
    adminArea: 'State of Rio Grande do Norte',
    streetNumber: null,
    country: 'Brazil',
    countryCode: 'BR',
    postalCode: '59178-000',
    subAdminArea: null,
    formattedAddress: 'Tibau do Sul - State of Rio Grande do Norte, 59178-000, Brazil',
    subLocality: null },
  { streetName: null,
    feature: 'State of Rio Grande do Norte',
    locale: 'en_US',
    locality: null,
    position: { lng: -36.954107, lat: -5.4025803 },
    adminArea: 'State of Rio Grande do Norte',
    streetNumber: null,
    country: 'Brazil',
    countryCode: 'BR',
    postalCode: null,
    subAdminArea: null,
    formattedAddress: 'State of Rio Grande do Norte, Brazil',
    subLocality: null },
  { streetName: null,
    feature: 'Brazil',
    locale: 'en_US',
    locality: null,
    position: { lng: -51.92528, lat: -14.235004 },
    adminArea: null,
    streetNumber: null,
    country: 'Brazil',
    countryCode: 'BR',
    postalCode: null,
    subAdminArea: null,
    formattedAddress: 'Brazil',
    subLocality: null },
  { streetName: 'Rua Flores da Mata',
    feature: null,
    locale: 'en_US',
    locality: 'Tibau do Sul',
    position: { lng: -35.0597249, lat: -6.2296355 },
    adminArea: 'State of Rio Grande do Norte',
    streetNumber: null,
    country: 'Brazil',
    countryCode: 'BR',
    postalCode: '59178-000',
    subAdminArea: null,
    formattedAddress: 'Rua Flores da Mata, Tibau do Sul - RN, 59178-000, Brazil',
    subLocality: null } ]
`

Thanks in advance.

**Comment by devfd** [comment]
> What is Geocoding?
> Geocoding is the process of converting addresses (like "1600 Amphitheatre Parkway, Mountain View, CA") into geographic coordinates (like latitude 37.423021 and longitude -122.083739), which you can use to place markers on a map, or position the map.

from https://developers.google.com/maps/documentation/geocoding/intro
let me know if you have any outstanding issues using the lib
