### ISSUE TITLE
Prod build failed - Failed to minify the code from this file:  ./node_modules/react-geocode/lib/index.js:1

### ISSUE THREAD

**Issue by GuillaumeRx** [devfd/react-native-geocoder#71]
Logs : 

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'build' ]
2 info using npm@5.8.0
3 info using node@v8.9.1
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle pharma-express-v2@0.1.0~prebuild: pharma-express-v2@0.1.0
6 info lifecycle pharma-express-v2@0.1.0~build: pharma-express-v2@0.1.0
7 verbose lifecycle pharma-express-v2@0.1.0~build: unsafe-perm in lifecycle true
8 verbose lifecycle pharma-express-v2@0.1.0~build: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/guillaume/Documents/Web Developpement/React/pharma-express/node_modules/.bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin
9 verbose lifecycle pharma-express-v2@0.1.0~build: CWD: /Users/guillaume/Documents/Web Developpement/React/pharma-express
10 silly lifecycle pharma-express-v2@0.1.0~build: Args: [ '-c', 'react-scripts build' ]
11 silly lifecycle pharma-express-v2@0.1.0~build: Returned: code: 1  signal: null
12 info lifecycle pharma-express-v2@0.1.0~build: Failed to exec build script
13 verbose stack Error: pharma-express-v2@0.1.0 build: `react-scripts build`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:283:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid pharma-express-v2@0.1.0
15 verbose cwd /Users/guillaume/Documents/Web Developpement/React/pharma-express
16 verbose Darwin 17.4.0
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build"
18 verbose node v8.9.1
19 verbose npm  v5.8.0
20 error code ELIFECYCLE
21 error errno 1
22 error pharma-express-v2@0.1.0 build: `react-scripts build`
22 error Exit status 1
23 error Failed at the pharma-express-v2@0.1.0 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by shraddhabhatt** [comment]
How you fixed it

**Comment by somasatish** [comment]
I am still facing the issue, what is the resolution to the issue, unable to solve even after deleting and rebuilding the "Build" folder
