### ISSUE TITLE
npm version is different that github version

### ISSUE THREAD

**Issue by patoroco** [devfd/react-native-geocoder#8]
Hi,

`react-native-geocoder` v0.14.0 is different between npmjs.com and github repo.

I discovered that because github repo has `android` folder, but when I use npm install from npmjs server, it doesn't download this folder. I was looking the `.npmignore` file (which I discovered that it doesn't make sense and open a #7) and I didn't found any references there to `android` folder, so I try to download directly from this repo. Result is bellow.

Left side is using `npm install react-native-geocoder` (from npmjs.com), and right side is using `npm install devfd/react-native-geocoder`
<img width="471" alt="screen shot 2015-12-16 at 12 58 22" src="https://cloud.githubusercontent.com/assets/701909/11840279/dfb745ee-a3f4-11e5-9043-73ed37610e4d.png">

Also should be good if you'd accept #6  because it included interesting info about how to install on Android.

Thanks for your library!

**Comment by devfd** [comment]
all good now, v0.2.0 has just been published to npm

**Comment by patoroco** [comment]
Thanks!
