### ISSUE TITLE
Android: Failed to execute aapt on release build

### ISSUE THREAD

**Issue by christiandrey** [devfd/react-native-geocoder#82]
Hi, guys.

I tried to create a release build, and got the error below.

`Execution failed for task ':react-native-geocoder:verifyReleaseResources'.
com.android.ide.common.process.ProcessException: Failed to execute aapt`

The obvious solution would be to disable aapt, but I can't do that because a couple of other libraries i have used in my project require aapt to be enabled.

I use react-native v0.56.0 and react-native-geocoder v0.5.0.

I was wondering if anyone else has run into this same issue, and the steps needed to fix this.

Thank you.

**Comment by martingalovic** [comment]
same here

**Comment by mertozylmz** [comment]
Hi,  @christiandrey and @martingalovic 
You can solve this problem.
You must change these parameters as follows
Open `react-native-geocoder -> build.gradle` and 
```
compileSdkVersion = 26 // This need to change
...
targetSdkVersion = 26 // This need to change
```

Because I've had the same problem :)

**Comment by christiandrey** [comment]
This works fine, thank you!

**Comment by vishalTechnoFreek** [comment]
Hi @mozaik1  after following the steps given by you I am still facing same issue.

**Comment by fyodoriv** [comment]
This helped me https://github.com/facebook/react-native/issues/19239#issuecomment-390225700
